@baseUrl = http://localhost:8000

## Health Check
GET {{baseUrl}}/health

### User Creation
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### User Token Creation
# @name login
POST {{baseUrl}}/users/token
Content-Type: application/x-www-form-urlencoded

username=john.doe@example.com&password=password123

### Token Extraction
@token = {{login.response.body.access_token}}

### Get User Profile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

### Subscription Plan Selection
POST {{baseUrl}}/subscription/select-plan
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "plan_id": 1
}

### Get User Plans
GET {{baseUrl}}/subscription/user
Authorization: Bearer {{token}}

### Movement Creation
POST {{baseUrl}}/movement/bank-accounts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "My Bank Account",
  "bank_name": "Banco do Brasil",
  "account_number": "123456",
  "initial_balance": 1000.00
}
